AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::SecretsManager-2024-09-16
Description: RDS MySQL + Secrets Manager + hosted rotation lab

Resources:

  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: rds-mysql-admin-secret
      Description: Admin credentials for RDS MySQL
      GenerateSecretString:
        SecretStringTemplate: '{"username":"admin"}'
        GenerateStringKey: password
        PasswordLength: 20
        ExcludeCharacters: '"@/\'

  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: my-rotation-lab-db
      Engine: mysql
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      MasterUsername: !Sub '{{resolve:secretsmanager:${DBSecret}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBSecret}:SecretString:password}}'
      PubliclyAccessible: false
      BackupRetentionPeriod: 0
      MultiAZ: false

  DBSecretAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref DBSecret
      TargetId: !Ref MyDB
      TargetType: AWS::RDS::DBInstance

  SecretRotation:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: DBSecretAttachment
    Properties:
      SecretId: !Ref DBSecret
      HostedRotationLambda:
        RotationType: MySQLSingleUser
        RotationLambdaName: MyRotationLambda
      RotationRules:
        AutomaticallyAfterDays: 90
